server:
  port: 8080

spring:
  application:
    name: recipe_app

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: recipe_user
    password: recipe_user
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
